### PR TITLE
Issue13 - Right Click Options

### PR DESCRIPTION
**Pull request by SarahL88**
There are two problems (listed below).  I think they involve the library - not sure.  We can discuss.

1) for 3 example cyclical peptides on 'load' modal: 
A) image doesn't show
B) molecular properties don't show

2) for 3rd example sequence on 'load' modal: error trying to get Canonical HELM

Thanks,
Sarah

### CODE REVIEW

**Comment by thankam** [comment]
In the current editor, for the example 3 from modal dialog, it shows 2 rows for each sequence.

**Comment by jsanford8** [comment]
Hey Sarah,

I made a couple of quick edits to get the build to pass, but nothing
substantial. I'll have to take a look at this more in depth tomorrow to see
what's going on. We can also talk about this tomorrow during our call.

Thanks!
Justin

**Comment by sabhilash** [comment]
Regarding example 3 sequence: PEPTIDE1{T.R.L}|PEPTIDE2{R.Y.R}$PEPTIDE1,PEPTIDE1,3:R2-1:R1|PEPTIDE2,PEPTIDE2,3:R2-1:R1$$$

Looks like the webservice does not support the above and it errors out for molecular weight, formula and chemical structure image. 

http://104.236.250.11:8080/WebService/service/Calculation/MolecularWeight/%20PEPTIDE1%7BT.R.L%7D%7CPEPTIDE2%7BR.Y.R%7D%24PEPTIDE1%2CPEPTIDE1%2C3%3AR2-1%3AR1%7CPEPTIDE2%2CPEPTIDE2%2C3%3AR2-1%3AR1%24%24%24

However, the webservice returns a single extinction coefficient value and thar is displayed as a single row.

**Comment by SarahL88** [comment]
Hi Justin,
Yes - sounds like there are some things to discuss on this.  We can talk tonight.
Thanks,Sarah

**Comment by cokongwu** [comment]
What are your thoughts on this? Would you like some help or is there a
section of the code that you think could use some fresh eyes?

Chinedu

**Comment by SarahL88** [comment]
Hi Chinedu,
Let's talk about this tonight.
Thanks,Sarah

**Comment by sabhilash** [comment]
Added error checks for invalid images and invalid canonical helm; updated webservice image methods and corresponding tests.

**Comment by jsanford8** [comment]
fixes #13

**Pull request merged**
